blog_app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home_view, name='home'),
    path('about/', views.about_view, name='about'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('users/', include('users.urls')),
]

if settings.DEBUG:
  urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views

app_name = 'users'
urlpatterns = [
  path('', views.indexView.as_view(), name='index'),
  path('signup/', views.SignUpView.as_view(), name='signup'),
  path('edit/', views.EditView.as_view(), name='edit'),
  # path('login', views.login, name='login'),
  path('<int:user_id>/', views.show, name='show'),
]

posts/models.py
from django.db import models
from users.models import User
from django.contrib.auth import get_user_model

Author = get_user_model()

# Create your models here.
class Post(models.Model):
  author_id = models.ForeignKey(Author, on_delete=models.CASCADE)
  title = models.CharField(blank=False, null=False, max_length=200)
  text = models.TextField(blank=False, null=False)
  comments_counter = models.PositiveIntegerField(default=0, verbose_name='Comments counter')
  likes_counter = models.PositiveIntegerField(default=0, verbose_name='Likes counter')
  created_at = models.DateTimeField(auto_now_add=True)
  updated_at = models.DateTimeField(auto_now=True)

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
from PIL import Image
from django.utils.translation import gettext_lazy as _
from .managers import UserManager
# from django.contrib.auth import get_user_model
# User = get_user_model()

# Create your models here.
class User(AbstractBaseUser, PermissionsMixin):
  username = None
  name = models.CharField(_('user_name'), blank=False, null=False)
  email = models.EmailField(_('email_address'), unique=True, max_length=200)
  photo = models.ImageField(upload_to='profiles', blank=True, null=True, verbose_name='photo')
  bio = models.TextField(blank=True, null=True, verbose_name='Biograthy')
  posts_counter = models.PositiveIntegerField(default=0, null=False, verbose_name='posts counter')
  created_at = models.DateTimeField(auto_now_add=True)
  updated_at = models.DateTimeField(auto_now=True)
  is_staff = models.BooleanField(default=False)
  is_active = models.BooleanField(default=True)

  USERNAME_FIELD = 'email'
  REQUIRED_FIELDS = []

  objects = UserManager()

  def has_perm(self, perm, obj=None):
    return True
  
  def save(self, *args, **kwargs):
    super().save()
    if self.photo:
      img = Image.open(self.photo.path)

      if img.height > 80 or img.width > 80:
        new_img = (80, 80)
        img.thumbnail(new_img)
        img.save(self.photo.path)
  # def is_staff(self):
  #   return self.staff
  
  @property
  def is_admin(self):
    return self.is_superuser
  
  def __str__(self):
    return self.email
  

users/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.db.models import fields
from django import forms
from .models import User
from django.contrib.auth import get_user_model

Author = get_user_model()
# from django.contrib.auth.models import User
# from django.core.exceptions import ValidationError
# from django.contrib.auth.forms import UserCreationForm

class CustomUserCreationForm(UserCreationForm):
  # first_name = forms.CharField(label='First name', min_length=2, max_length=100)
  # last_name = forms.CharField(label='Last name', min_length=2, max_length=100)
  # username = forms.CharField(label='Username', min_length=5, max_length=150)
  # email = forms.EmailField(label='Email')
  password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
  password2 = forms.CharField(label='Confirm Password', widget=forms.PasswordInput)

  class Meta:
    model = User
    fields = ('email', 'name', 'bio',)

  # def username_clean(self):  
  #   username = self.cleaned_data['username'].lower()  
  #   new = Author.objects.filter(username = username)  
  #   if new.count():  
  #     raise forms.ValidationError("User Already Exist")  
  #   return username  
  
  def clean_email(self):  
    email = self.cleaned_data.get('email') 
    user = Author.objects.filter(email=email)  
    if user.exists():  
      raise forms.ValidationError("Email Already Exist")  
    return email  
  
  # def clean_password2(self):  
  #   password1 = self.cleaned_data['password1']  
  #   password2 = self.cleaned_data['password2']  
  
  #   if password1 and password2 and password1 != password2:  
  #     raise forms.ValidationError("Password don't match")  
  #   return password2  

  def clean(self):
    cleaned_data = super().clean()
    password1 = cleaned_data.get('password1')
    password2 = cleaned_data.get('password2')

    if password1 is not None and password1 != password2:
      self.add_error('password2', 'Your passwords must match')
    return cleaned_data
  
  def save(self, commit = True):
    user = super().save(commit=False)
    user.set_password(self.cleaned_data['password1'])
    if commit:
      user.save()
    return user
  
    # user = Author.objects.create_user(  
    #   # self.cleaned_data['first_name'],
    #   # self.cleaned_data['last_name'],
    #   self.cleaned_data['username'],  
    #   self.cleaned_data['email'],  
    #   self.cleaned_data['password1']  
    # )  
    # return user

class CustomUserChangeForm(UserChangeForm):
  class Meta:
    model = User
    fields = ('name', 'photo', 'bio',)
  
class LoginForm(forms.Form):
  email = forms.EmailField(label="Enter email")
  password = forms.CharField(label='Enter password', widget=forms.PasswordInput)

blog_app/views.py
from django.http import HttpResponse
from django.shortcuts import render

def home_view(request):
  return render(request, 'home.html')

def about_view(request):
  return render(request, 'about.html')

posts/views.py
from django.shortcuts import render

# Create your views here.

users/views.py
from django.contrib.auth import get_user_model
User = get_user_model()
from django.shortcuts import render, get_object_or_404
from django.contrib import messages
from .forms import CustomUserCreationForm, CustomUserChangeForm
from django.http import HttpResponseRedirect
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate
from django.urls import reverse, reverse_lazy
from django.views import generic
# from .forms import CustomUserCreationForm
# Create your views here.
class indexView(generic.ListView):
  model = User
  template_name = 'users/index.html'
  context_object_name = "users"

  def get_queryset(self):
    return User.objects.all().order_by('-updated_at')

  # return render(request, 'users/index.html')

class SignUpView(generic.CreateView):
  form_class = CustomUserCreationForm
  success_url = reverse_lazy('login')
  template_name = 'registration/signup.html'
  # print(dir(request))
  # if request.method == 'POST':
  #   form = UserCreationForm(request.POST)
  #   print(form.is_valid())  
  #   # if form.is_valid():
  #   #   user = form.save()
  #   #   messages.success(request, 'Account Created successfully')
  #   #   return HttpResponseRedirect(reverse("users:show", args=(user.id)))
  # else:
  #   form = UserCreationForm()

  # context = {
  #   'form':form
  # }
  # return render(request, 'users/register.html', context)

# def login(request):
#   if request.method == 'POST':
#     pass
#   user = LoginForm()
#   return render(request, 'users/login.html', {'form':user})
# @login_required
def show(request, user_id):
  user = get_object_or_404(User, pk=user_id)
  return render(request, 'users/show.html', { 'user':user})

class EditView(LoginRequiredMixin, generic.edit.UpdateView):
  model = User
  form_class = CustomUserChangeForm
  template_name = 'registration/edit.html'

  def get_object(self):
    return self.request.user
  
  def get_success_url(self):
    return reverse_lazy('users:show', args=[self.request.user.id])

templates/about.html
{% extends 'layout.html' %}

{% block title %}
  About page
{% endblock %}

{% block body %}
  <h1>This the about page</h1>
  <p>Checkout my <a href="{% url 'home' %}">home</a> page</p>
{% endblock %}

templates/home.html
{% extends 'layout.html' %}

{% block title %}
  Home page
{% endblock %}

{% block body %}
  <h1>This the home page</h1>
  <p>Checkout my <a href="{% url 'users:index' %}">User page</a> page</p>
{% endblock %}

templates/layout.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>
    {% block title %}
      Blog App
    {% endblock %}
  </title>
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body>
  <header>
    <ul class="social-images">
      <li><a href="#"><img src="{% static 'images/facebook.webp' %}" alt="facebook"></a></li>
      <li><a href="#"><img src="{% static 'images/github.png' %}" alt="github"></a></li>
      <li><a href="#"><img src="{% static 'images/instagram.webp' %}" alt="instagram"></a></li>
    </ul>
  </header>
  <nav>
    <a href="{% url 'home' %}">Logo</a>
    <ul>
      <li><a href="{% url 'home' %}">Home</a></li>
      <li><a href="{% url 'about' %}">About</a></li>
      {% if user.is_authenticated %}
        <li><a href="{% url 'users:show' user.id %}">{{user.name}}</a></li>
        <li><a href="{% url 'users:edit' %}">Edit</a></li>
        <li>
          <form action="{% url 'logout' %}" method="post">
            {% csrf_token %}
            <button type="submit" class="btn btn-danger">Log Out</button>
          </form>
        </li>
      {% else %}
        <li><a href="{% url 'login' %}">Log In</a></li>
        <li><a href="{% url 'users:signup' %}">Sign In</a></li>
      {% endif %}
    </ul>
  </nav>
  <main>
    {% block body %}
    {% endblock %}
  </main>
  <footer>
    <p>@ 2024 </p>
  </footer>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>

users/templates/users/_user.html
<a href="{% url 'users:show' user.id %}" class="user p-2 m-2">
  {% if user.photo %}
    <img class="col" src="{{user.photo.url}}" alt="User profile">
  {% else %}
    <img class="col" src="/media/profiles/default.png" alt="User profile">
  {% endif %}
  <div class="col row border py-2">
    <strong>{{user.name}}</strong>
    <p class="fw-lighter text-end">Posts Counter: {{user.posts_counter}}</p>
  </div>
</a>

users/templates/users/index.html
{% extends 'layout.html' %}

{% block title %}
  Users
{% endblock %}

{% block body %}
  <h1>This the users page</h1>
  {% for user in users %}
    {% include "users/_user.html" with user=user  %}
  {% endfor %}
{% endblock %}

users/templates/users/show.html
{% extends "layout.html" %}

{% block title %}
  {{user.name}}
{% endblock %}

{% block body %}
  <section class="show-user">
    {% include 'users/_user.html' with user=user %}
    <div class="bio border">
      <strong>Bio</strong>
      <p>
        {{user.bio}}
      </p>
    </div>
    <div class="post">
      <strong>Post #1</strong>
      <p>
        Lorem ipsum dolor sit, amet consectetur adipisicing elit. Aliquid nesciunt commodi magni veritatis voluptates libero, dignissimos, ipsam debitis reprehenderit, doloribus modi. Similique, obcaecati! Autem sint iusto sapiente illum at quidem?
      </p>
    </div>
    <div class="post">
      <strong>Post #2</strong>
      <p>
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Eum accusamus praesentium nisi delectus reprehenderit hic quibusdam et voluptates illo, tenetur saepe accusantium amet facilis illum laborum fugit architecto debitis earum.
      </p>
    </div>
    <div class="post">
      <strong>Post #3</strong>
      <p>
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Tenetur soluta consectetur, ducimus aliquam commodi nisi nobis esse rem, accusamus nemo similique nihil eveniet accusantium eaque asperiores tempore impedit nostrum provident!
      </p>
    </div>
    <button type="button" class="btn btn-outline-secondary">See all posts</button>
  </section>
{% endblock %}